- name: Update all packages to the latest version
  sudo: true
  hosts: all
  tasks:

    - name: "Upgrade existing packages"
      apt: 
        update_cache: yes 
        cache_valid_time: 3600
        upgrade: yes 

    - name: Install pip if not present
      apt:
        name: python-pip
        state: present

    - name: Install GO if not present
      apt:
        name: golang-go
        state: present

    - name: Install open-jdk
      apt:
        name: default-jdk-headless
        state: present

    - name: Install Ruby if not present
      apt:
        name: ruby-full
        state: present

    - name: "Remove old packages"
      apt: 
        autoclean: yes
             
